version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "eclipse-temurin"
      update-types: [ "version-update:semver-major" ]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
