name: Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'abandoned-*'

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "mahoney266/slack-github-gha"
          install: true

      - uses: docker/build-push-action@v6
        with:
          target: build-output
          outputs: 'type=local,dest=build'

      - uses: docker/build-push-action@v6
        if: ${{ hashFiles('build/failed') != '' }}

      - uses: Mahoney-github-actions/gradle-build-output@v1
