name: Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'abandoned-*'

permissions:
  checks: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Build docker image name
        run: |
          echo "docker_image_name=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "mahoney266/lidalia-world-gha"
          install: true

      - uses: docker/build-push-action@v6
        with:
          target: build-output
          outputs: 'type=local,dest=build'

      - uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64/v8,linux/amd64
          tags: ghcr.io/${{ env.docker_image_name }}:${{ github.sha }}
          push: true

      - run: docker run --rm ghcr.io/${{ env.docker_image_name }}:${{ github.sha }}

      - uses: Mahoney-github-actions/gradle-build-output@v1
