name: Build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'abandoned-*'

permissions:
  checks: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Build docker image name
        run: |
          echo "docker_image_name=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "mahoney266/lidalia-world-gha"

      - uses: docker/build-push-action@v6
        with:
          context: .
          target: build-output
          provenance: false
          outputs: 'type=local,dest=build'

      - uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          tags: ${{ env.docker_image_name }}:${{ github.sha }}

      - run: docker run --rm ${{ env.docker_image_name }}:${{ github.sha }} --test

      - uses: Mahoney-github-actions/gradle-build-output@v1
        with:
          artifacts_dir: build/project/artifacts
